config/routes.rb
Rails.application.routes.draw do
  root to: 'user#index'
  resources :user, only: [:show, :new, :create]
  resources :session, only: [:new, :create, :destroy]
  resources :event, only: [:index, :new, :create, :show, :destroy]
  resources :attendee, only: [:create, :destroy]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :attendees
  has_many :users, through: :attendees
  validates :datetime, presence: true, date: { after_or_equal_to: Time.zone.now }
  validates :location, presence: true, length: { minimum: 4, message: 'Location is too short...' }

  scope :past, -> { where('datetime < ?', Time.zone.now) }
  scope :future, -> { where('datetime >= ?', Time.zone.now) }
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  def index
    @events_past = Event.past.order('datetime DESC')
    @events_future = Event.future.order('datetime ASC')
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.authored_events.build(event_params)
    if @event.save
      flash[:success] = 'Event was created succesfully.'
      redirect_to event_path(@event.id)
    else
      flash[:danger] = 'Location must have more than 4 characters and date must be correct.'
      redirect_to new_event_path
    end
  end

  def show
    @event = Event.find(params[:id])
    @users = @event.users
    @attendee = Attendee.new
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.author == current_user && @event.destroy
      flash[:success] = 'Event deleted successfully'
      redirect_to user_path(current_user)
    else
      flash[:danger] = 'Event not destroyed'
      redirect_to event_path
    end
  end

  private

  def event_params
    params.require(:event).permit(:location, :datetime)
  end
end

app/views/event/_assist_badge.html.erb
<%= form_with model: @attendee, method: :post, url: attendee_index_path do |f| %>
  <%= f.hidden_field :user_id, :value => current_user[:id] %>
  <%= f.hidden_field :event_id, :value => params[:id] %> 
  <%= f.submit 'I will assist', class: 'btn btn-success' %><br>
<% end %>

app/views/event/_assist_btn.html.erb
<%= form_with model: @attendee, method: :post, url: attendee_index_path do |f| %>
  <%= f.hidden_field :user_id, :value => current_user[:id] %>
  <%= f.hidden_field :event_id, :value => params[:id] %> 
  <%= f.submit 'I will assist', class: 'btn btn-success' %><br>
<% end %>

app/views/event/_new_event_form.html.erb
<%= form_with model: @event, url: event_index_path do |f| %>
  <%= label_tag(:location, "Location:", class: 'lead') %></br>
  <%= f.text_field :location, class: "form-control mx-auto w-25 border border-dark" %></br>
  <%= label_tag(:datetime, "Date", class: 'lead') %></br>
  <%= f.datetime_field :datetime, class: "form-control mx-auto w-25 border border-dark" %></br></br>
  <%= f.submit 'Create Event', class: 'btn btn-success' %>
<% end %>

app/views/event/_unassist_badge.html.erb
<%= form_with model: @attendee, method: :delete, url: attendee_path do |f| %>
  <%= f.hidden_field :user_id, :value => current_user[:id] %>
  <%= f.hidden_field :event_id, :value => params[:id] %> 
  <%= f.submit 'I will not assist', class: 'btn btn-danger' %><br>
<% end %>

app/views/event/_unassist_btn.html.erb
<%= form_with model: @attendee, method: :delete, url: attendee_path do |f| %>
  <%= f.hidden_field :user_id, :value => current_user[:id] %>
  <%= f.hidden_field :event_id, :value => params[:id] %> 
  <%= f.submit 'I will not assist', class: 'btn btn-danger' %><br>
<% end %>

app/views/event/index.html.erb
<div class="w-75 mx-auto text-center mt-4">

  <h1 class="display-4">These are all the events</h1>
  <h5 class="text-danger"><%= 'Sign in to view more information!' unless signed_in? %></h2>

  <div class="row">
    <div class="col-4">
    <h2 class="my-4"><span class="badge badge-secondary">Past events:</span></h3>
    <ul class="p-0 text-muted">
      <% list_events(@events_past) %>
    </ul> 
    </div>
    <div class="col-8">
    <h2 class="my-4"><span class="badge badge-dark">Future events:</span></h3>
    <ul class="p-0 font-weight-bold">
      <% list_events(@events_future) %>
    </ul>
    </div>
  </div>
</div>

app/views/event/new.html.erb
<div class="w-50 mx-auto mt-5 text-center">  
  <h1 class="display-4">Create Event</h1>
  <%= render 'new_event_form'%>
</div>

app/views/event/show.html.erb
 <div class="w-50 mx-auto mt-5 text-center">
  <h1 class="display-4">Event details</h1><br>
  <div class="text-center w-75 mx-auto">
    <h2><span class="font-weight-light small">Location:</span><br> <%= @event.location %></h1>
    <h2><span class="font-weight-light small">Date:</span><br> <%= @event.datetime.strftime("On %m/%d/%Y, at %I:%M%p") %></h1><br>
  </div>
  <h3> Attendees: </h3>
    <ul class="list-group w-25 mx-auto mb-4 mt-4">
      <% show_attendees(@users) %>
    </ul>

  <% assistance_btn(params[:id]) %><br>

  <%= link_to 'Back to Events list', event_index_path %> <br>
  <%= link_to 'Back to My Events', user_path(current_user) %>
</div>