config/routes.rb
Rails.application.routes.draw do
  root to: 'user#index'
  resources :user, only: [:show, :new, :create]
  resources :session, only: [:new, :create, :destroy]
  resources :event, only: [:index, :new, :create, :show, :destroy]
  resources :attendee, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendees
  has_many :attended_events, through: :attendees, foreign_key: 'event_id', source: :event

  has_many :authored_events, foreign_key: 'author_id', class_name: 'Event'

  validates :name, presence: true, uniqueness: true, length: { minimum: 4, message: 'Name is too short...' }
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index; end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:danger] = 'User name must have at least 4 characters. Or name has already been taken. Try again.'
      redirect_to new_user_path
      # render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/views/user/_form.html.erb
<%= form_with model: @user, url: user_index_path do |f| %>
  <%= label_tag(:name, "Input a new user name:", class: 'lead') %><br>
  <%= f.text_field :name, class: "mb-4 form-control mx-auto w-25 border border-dark" %><br>
  <%= f.submit 'Create User', class: "btn btn-warning" %>
<% end %>

app/views/user/index.html.erb
<div class="text-center w-50 mx-auto mt-5">
<% if signed_in? %>
  <h1 class='display-4 mb-3'>Welcome <%= current_user.name %>!</h1>
  <p class="mb-4 lead">What you wanna do?</p>
  <%= button_to 'Create a New Event', new_event_path, method: :get, class: 'btn btn-success' %></br>
  <div class="row">
    <div class="col-2 ml-auto">
      <%= button_to 'My events', user_path(current_user.id), method: :get, class: 'btn btn-info' %>
    </div>
    <div class="col-2 mr-auto">
      <%= button_to 'All events', event_index_path, method: :get, class: 'btn btn-info' %></br>
    </div>
  </div>
  <%= button_to 'Sign Out ', session_path(current_user), method: :delete, class: 'btn btn-danger' %>
<% else %>
  <h1 class='display-4'>Welcome</h1>
    <p class='lead'>Sign in to see the options</p>
    <%= button_to 'Sign In', new_session_path, method: :get, class: 'btn btn-success' %></br>
    <%= button_to 'Register', new_user_path, method: :get, class: 'btn btn-warning' %>
<% end %>
</div>

app/views/user/new.html.erb
<div class="w-50 mx-auto text-center mt-5">
  <h1 class="display-4">Create New User:</h1></br>
  <%= render 'form' %>
</div>

app/views/user/show.html.erb
<div class="w-75 mx-auto mt-5">

  <h1 class="text-center display-4 mb-4">Your events, <%= @user.name %></h1>
  <h3>Created Events:</h3>
  <div class="row">
    <% all_my_events(@user.authored_events) %>
  </div>
  <hr>
  <h3 class="mt-4">Next events (will assist):</h3>
  <div class='row'>
  <% my_future_events(@user.attended_events) %>
  </div>
  <hr>
  <h3 class="mt-4 text-muted">Past events (assisted):</h3>
  <div class='row text-muted'>
    <% my_past_events(@user.attended_events) %>
  </div>
</div>