config/routes.rb
Rails.application.routes.draw do
  root to: 'user#index'
  resources :user, only: [:show, :new, :create]
  resources :session, only: [:new, :create, :destroy]
  resources :event, only: [:index, :new, :create, :show, :destroy]
  resources :attendee, only: [:create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'Private Events', root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto col-8">
          <% if signed_in? %> 
          <li class="nav-item active">
            <%= link_to 'Home', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to 'My Events', user_path(current_user.id), class: 'nav-link' %>
          </li>
          <% end %>
          <li class="nav-item active">
            <%= link_to 'All Events', event_index_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
          <% unless signed_in? %> 
            <%= link_to 'Sign In', new_session_path, class: 'nav-link' %>
          <% end %>
          </li>
          <li class="nav-item">
          <% unless signed_in? %> 
            <%= link_to 'Sign Up', new_user_path, class: 'nav-link' %>
          <% end %>
          </li>
          <% if signed_in? %> 
          <li class="nav-item active">
            <%= button_to 'New Event', new_event_path, method: :get, class: 'btn btn-success' %>
          </li>
          <% end %>
        </ul>
        <div class="my-2 my-lg-0 col-4">
          <%= render 'signed_in' %>
        </div>
      </div>
    </nav>
    
  <% flash.each do |type, msg| %>
    <div class="alert alert-<%= type %> alert-dismissible" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </div>
  <% end %>

    <%= yield %>
  </body>
</html>